// Generated stub for eval-runner CLI
// This file is normally generated by the build process

export const LOCALES = ['en-US'];
export const BUNDLED_LOCALES = ['en-US'];
export const DEFAULT_LOCALE = 'en-US';
export const REMOTE_FETCH_PATTERN = '';
export const LOCAL_FETCH_PATTERN = './locales/@LOCALE@.json';
